node-placements:
  - node1:
    - home-timeline-redis
    - post-storage-memcached
    - user-timeline-redis
  - node2:
    - nginx-thrift
    - text-service
    - unique-id-service
    - url-shorten-memcached
    - url-shorten-mongodb
    - user-mention-service
    - user-mongodb
  - node3:
    - jaeger
    - media-mongodb
    - media-service
    - social-graph-redis
    - social-graph-service
    - user-memcached
  - node4:
    - media-memcached
    - post-storage-mongodb
    - url-shorten-service
    - user-service
    - user-timeline-service
  - node5:
    - compose-post-service
    - home-timeline-service
    - media-frontend
    - post-storage-service
    - social-graph-mongodb
    - user-timeline-mongodb